FROM tomcat:7.0

#ADD ? ?
#ADD ?.war /usr/local/tomcat/webapps/?.war
#ADD hibernate.cfg.xml /usr/local/tomcat/webapps/?/WEB-INF/classes/hibernate.cfg.xml

RUN mkdir -p /usr/local/goobi/config/
#RUN chmod 777 /usr/local/goobi/config/

RUN mkdir -p /usr/local/goobi/debug/
#RUN chmod 777 /usr/local/goobi/debug/

RUN mkdir -p /usr/local/goobi/import/
#RUN chmod 777 /usr/local/goobi/import/

RUN mkdir -p /usr/local/goobi/logs/
#RUN chmod 777 /usr/local/goobi/logs/

RUN mkdir -p /usr/local/goobi/messages/
#RUN chmod 777 /usr/local/goobi/messages/

RUN mkdir -p /usr/local/goobi/metadata/
#RUN chmod 777 /usr/local/goobi/metadata/

RUN mkdir -p /usr/local/goobi/plugins/
#RUN chmod 777 /usr/local/goobi/plugins/

RUN mkdir -p /usr/local/goobi/plugins/command/
#RUN chmod 777 /usr/local/goobi/plugins/command/

RUN mkdir -p /usr/local/goobi/plugins/import/
#RUN chmod 777 /usr/local/goobi/plugins/import/

RUN mkdir -p /usr/local/goobi/plugins/opac/
#RUN chmod 777 /usr/local/goobi/plugins/opac/

RUN mkdir -p /usr/local/goobi/plugins/step/
#RUN chmod 777 /usr/local/goobi/plugins/step/

RUN mkdir -p /usr/local/goobi/plugins/validation/
#RUN chmod 777 /usr/local/goobi/plugins/validation/

RUN mkdir -p /usr/local/goobi/rulesets/
#RUN chmod 777 /usr/local/goobi/rulesets/

RUN mkdir -p /usr/local/goobi/scripts/
#RUN chmod 777 /usr/local/goobi/scripts/

RUN mkdir -p /usr/local/goobi/swap/
#RUN chmod 777 /usr/local/goobi/swap/

RUN mkdir -p /usr/local/goobi/temp/
#RUN chmod 777 /usr/local/goobi/temp/

RUN mkdir -p /usr/local/goobi/users/
#RUN chmod 777 /usr/local/goobi/users/

RUN mkdir -p /usr/local/goobi/xslt/
#RUN chmod 777 /usr/local/goobi/xslt/

RUN mkdir -p /usr/local/goobi/rulesets/
#RUN chmod 777 /usr/local/goobi/rulesets/

#ADD goobi_config.properties /usr/local/tomcat/webapps/?/WEB-INF/classes/goobi_config.properties










#ADD log4j.properties /usr/local/tomcat/webapps/?/WEB-INF/classes/log4j.properties