FROM mysql:5.5
ADD my.cnf /etc/mysql/my.cnf
ADD Goobi_setup_schema.sql /tmp/Goobi_setup_schema.sql
#ADD Goobi_setup_default.sql /tmp/Goobi_setup_default.sql
ADD Goobi_setup_regelsaetze.sql /tmp/Goobi_setup_regelsaetze.sql
ADD Goobi_setup_laufzettel.sql /tmp/Goobi_setup_laufzettel.sql
ADD Goobi_setup_benutzergruppen.sql /tmp/Goobi_setup_benutzergruppen.sql
ADD Goobi_setup_benutzergruppenmitgliedschaft.sql /tmp/Goobi_setup_benutzergruppenmitgliedschaft.sql
ADD Goobi_setup_ldapgruppen.sql /tmp/Goobi_setup_ldapgruppen.sql
ADD Goobi_setup_datentypen.sql /tmp/Goobi_setup_datentypen.sql