FROM mysql:5.5
ADD my.cnf /etc/mysql/conf.d/my.cnf
ADD default.sql /usr/local/mysql/scripts/default.sql
#CMD mysql -u $MYSQL_USER -p $MYSQL_PASSWORD $MYSQL_DATABASE < /usr/local/mysql/scripts/default.sql


